# Generated by Django 5.0.2 on 2024-02-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancerApp', '0004_category_expense_income_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
