# Generated by Django 5.0.2 on 2024-02-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancerApp', '0005_alter_expense_category_remove_income_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
